config/routes.rb
Rails.application.routes.draw do
  root to: "home#top" 

  get "login" => "users#login_form"
  post "login" => "users#login"
  post "/logout" => "users#logout"

  get "signup" => "users#new"
  post "users/create" => "users#create"
  get 'users/index' => "users#index"
  get "users/:id" => "users#show"
  get "users/:id/profile" => "users#show_profile"
  get "users/:id/edit" => "users#edit"
  get "users/:id/profile_edit" => "users#profile_edit"
  post "users/:id/update" => "users#update"
  post "users/:id/profile_update" => "users#profile_update"

  get "rooms/search" => "rooms#search"
  get 'rooms/index' => "rooms#index"
  get "rooms/new" => "rooms#new"
  post "rooms/create" => "rooms#create"
  get "rooms/:id" => "rooms#show"
  get "rooms/:id/edit" => "rooms#edit"
  post "rooms/:id/update" => "rooms#update"
  delete "rooms/:id/destroy" => "rooms#destroy"
  get "rooms/search" => "rooms#search"

  resources :reservations, except: [:show] do
    collection do
      post "confirm" => "reservations#confirm"
      # get ""  => "reservations#index"
    end
  end

  # post "reserves/create" => "reserves#create"
  # resources :reserves, except: [:show] do
  #   collection do
  #     post "confirm" => "reserves#confirm"
  #     get "index" => "reserves#index"
  #   end
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :reservations

    validates :name_room, {presence: true}
    validates :detail, {presence: true}
    validates :price, {presence: true}
    validates :address, {presence: true}
    mount_uploader :image_room, ImageUploader

    validate :price_check
    def price_check
        unless price.nil? || 0 < self.price then
            errors.add(:base, "一円以上にしてください")
        end
    end

    def self.ransackable_attributes(auth_object = nil)
        ["address", "created_at", "detail", "id", "image_room", "name_room", "price", "updated_at", "user_id"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["reservations"]
    end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
protect_from_forgery :except => [:destroy]
before_action :set_q, only: [:index, :search]

  def index
    @rooms = Room.all
    @rooms = Room.where(user_id: @login_user.id)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(
      name_room: params[:name_room],
      detail: params[:detail],
      price: params[:price],
      address: params[:address],
      image_room: params[:image_room],
      user_id: @login_user.id
    )
    if @room.save
      session[:room_id] = @room.id
      flash[:notice] = "施設登録が完了しました"
      redirect_to("/rooms/#{@room.id}")
    else
      render("rooms/new")
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.name_room = params[:name_room]
    @room.detail = params[:detail]
    @room.price = params[:price]
    @room.address = params[:address]
    @room.image_room = params[:image_room]
    @room.user_id = @login_user.id
    if @room.save
      flash[:notice] = "施設情報を編集しました"
      redirect_to("/rooms/#{@room.id}")
    else
      render("rooms/edit")
    end
  end

  def destroy
    @room = Room.find_by(id: params[:id])
    @room.destroy
    flash[:notice] = "施設情報を削除しました"
    redirect_to("/rooms/index")
  end

  def search
    @results = @q.result
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<p>施設情報の編集</p>
    <div class="form-body">
        <% @room.errors.full_messages.each do |message| %>
            <div class="form-error">
                <%= message %>
            </div>
        <% end %>
        
    <%= form_tag("/rooms/#{@room.id}/update", {multipart: true}) do %>
        <p>施設名</p>
            <input name="name_room" value="<%= @room.name_room %>">
        <p>詳細</p>
            <textarea name="detail"><%= @room.detail %></textarea>
        <p>料金</p>
            <input name="price" value="<%= @room.price,  min: 1 %>" type="number">
        <p>住所</p>
            <input name="address" value="<%= @room.address %>">
        <p>画像</p>
            <input name="image_room" value="<%= @room.image_room %>" type="file">
            <br/>
            <input type="submit" value="保存">
    <% end %>

app/views/rooms/index.html.erb
<h1>施設一覧</h1>
<table>
    <thead>
        <tr>
            <th>画像</th>
            <th>施設名</th>
            <th>紹介文</th>
            <th>料金</th>
            <th>作成日</th>
            <th colspan="2"></th>
        </tr>
    </thead>

    <tbody>
    <% @rooms.each do |room| %>
        <tr>
            <td>
                <% if room.image_room? %>
                    <%= image_tag room.image_room.url, size: '100' %>
                <% else %>
                    <%= image_tag 'default-room-image.png', size: '100' %>
                <% end %>
            </td>
            <td><%= room.name_room %></td>
            <td><%= room.detail %></td>
            <td><%= room.price %></td>
            <td><%= room.created_at %></td>
            <td><%= link_to '詳細はこちら', "/rooms/#{room.id}" %></td>
            <td><%= link_to '編集', "/rooms/#{room.id}/edit" %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/rooms/new.html.erb
<h1>新規登録</h1>
<div class="form-body">
        <% @room.errors.full_messages.each do |message| %>
            <div class="form-error">
                <%= message %>
            </div>
        <% end %>
        
<%= form_with url: rooms_create_path do |f| %>
<table>
    <tr>
        <th>施設名</th>
        <td><%= f.text_field :name_room %></td>
    </tr>

    <tr>
        <th>施設詳細</th>
        <td><%= f.text_area :detail %></td>
    </tr>

    <tr>
        <th>料金</th>
        <td><%= f.number_field :price,  min: 1 %></td>
    </tr>

    <tr>
        <th>住所</th>
        <td><%= f.text_field :address %></td>
    </tr>

    <tr>
        <th>施設画像</th>
        <td><%= f.file_field :image_room %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= f.submit "保存" %></li>
    </ul>
</div>
<% end %>

app/views/rooms/search.html.erb
<%= search_form_for @q, url: rooms_search_path do |f| %>
    <%= f.label :address_cont, 'エリア名を入力' %>
    <%= f.search_field :address_cont %>
    <%= f.label :name_room_or_detail_cont, 'キーワード名を入力' %>
    <%= f.search_field :name_room_or_detail_cont %>
    <br>
    <%= f.submit '検索' %>
<% end %>

<h1>検索結果</h1>
<table>
    <thead>
        <tr>
            <th>画像</th>
            <th>施設名</th>
            <th>住所</th>
            <th>紹介文</th>
            <th>料金</th>
            <th colspan="1"></th>
        </tr>
    </thead>

    <tbody>
        <% @results.each do |room| %>
            <tr>
                <td>
                <% if room.image_room? %>
                    <%= image_tag room.image_room.url, size: '100' %>
                <% else %>
                    <%= image_tag 'default-room-image.png', size: '100' %>
                <% end %>
                </td>
                <td><%= room.name_room %></td>
                <td><%= room.address %></td>
                <td><%= room.detail %></td>
                <td><%= room.price %></td>
                <td><%= link_to '詳細はこちら', "/rooms/#{room.id}" %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/rooms/show.html.erb
<div class="room">
    <% if @room.image_room? %>
        <%= image_tag @room.image_room.url, size: '100' %>
    <% else %>
        <%= image_tag 'default-room-image.png', size:"500x300" %>
    <% end %>
    <p>施設名&emsp;<%= @room.name_room %></p>
    <p>住所&emsp;<%= @room.address %></p>
    <p>価格&emsp;<%= @room.price %></p>
    <p>詳細&emsp;<%= @room.detail %></p>
</div>

<% @reservation.errors.each do |message| %>
    <div class="form-error">
        <%= message.full_message %>
    </div>
<% end %>

<%= form_with url: confirm_reservations_path , local: true do |f| %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <table>
    <tr>
        <th>チェックイン</th>
        <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
        <th>チェックアウト</th>
        <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
        <th>人数</th>
        <td><%= f.number_field :people,  min: 1%></td>
    </tr>

</table>
    <% if @login_user %>
        <li><%= f.submit "予約する"%></li>
        <li><%= link_to "戻る", :back %></li>
    <% else %>
        <li><button type="button" onclick="location.href='/login'">ログイン</button></li>
        <li><%= link_to "戻る", :back %></li>
    <% end %>
</ul>
<% end %>